diff -urN drm.orig/linux-core/Makefile drm/linux-core/Makefile
--- drm.orig/linux-core/Makefile	2005-05-02 23:36:46.000000000 -0400
+++ drm/linux-core/Makefile	2005-05-02 23:42:00.000000000 -0400
@@ -245,14 +245,17 @@
 $(MODULE_LIST)::
 	make DRM_MODULES=$@ modules
 
+install_for_gentoo:
+	mkdir -p $(DESTDIR)/lib/modules/$(RUNNING_REL)/kernel/drivers/char/drm
+	cp -p $(MODULE_LIST:.o=.ko) $(DESTDIR)/lib/modules/$(RUNNING_REL)/kernel/drivers/char/drm
+
 # Build test utilities
 
 PRGCFLAGS = $(CFLAGS) -g -ansi -pedantic -DPOSIX_C_SOURCE=199309L \
 	    -D_POSIX_SOURCE -D_XOPEN_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE \
-	    -I. -I../../..
+	    -I. -I../../.. -I../libdrm
 
-DRMSTATLIBS = -L../../.. -L.. -ldrm -lxf86_os \
-	      -L../../../../dummylib -ldummy -lm
+DRMSTATLIBS = -L../../.. -L.. -L../libdrm
 
 programs: $(PROGS)
 
@@ -260,7 +263,7 @@
 	$(CC) $(PRGCFLAGS) $< -o $@
 
 drmstat: drmstat.c
-	$(CC) $(PRGCFLAGS) $< -o $@ $(DRMSTATLIBS)
+	$(CC) $(PRGCFLAGS) $< -o $@ ../libdrm/*.o $(DRMSTATLIBS)
 
 else
 
