#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

PIDFILE=/var/run/razerd/razerd.pid

start() {
	ebegin "Starting razerd"
		start-stop-daemon --start --background \
			--pidfile ${PIDFILE} --exec /usr/sbin/razerd \
			--pidfile=${PIDFILE} --background
	eend $?
}

stop() {
	ebegin "Stopping razerd"
		start-stop-daemon --stop \
		--pidfile ${PIDFILE}
	eend $?
}

restart() {
	stop
	sleep 3
	start
}
